Feature/train 216
r-barlow/train-spring-boot-insight pull request #20
Opened 2023-04-12 07:40 UTC by r-barlow

2023-04-13 07:16 UTC, JOlsen-Neslo requested changes

2023-04-13 07:16 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +    private IUserRepository userRepository;
Following the pattern of marking everything final that can be final, I would mark this as a final variable and then initialise it in the constructor. The Autowiring will occur automatically

2023-04-13 07:16 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +public class UserController extends AGenericController<User, Long>{
Please make sure you format your files

2023-04-14 09:50 UTC, JOlsen-Neslo requested changes

2023-04-14 09:50 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +    public UserController(UserService service) {
Mark this as final

2023-04-14 09:50 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/service/UserService.java
> +    public User update(final User entity) {
Shouldn't there be a create method as well?

2023-04-14 09:54 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +    @Autowired
With the new version of spring, marking the constructor of a controller, service or repository annotated bean is redundant.

2023-04-14 10:20 UTC, JOlsen-Neslo approved these changes

2023-04-14 11:45 UTC, colsen-neslo approved these changes

2023-04-14 11:46 UTC, merged