TRAIN-242: Implement Spring Security
r-barlow/train-spring-boot-insight pull request #33
Opened 2023-04-18 14:10 UTC by r-barlow

2023-04-18 14:49 UTC, colsen-neslo requested changes

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/BasicAuthenticationFilter.java
> +    public static final String SEPARATOR = ":";
Are these constants accessed outside the scope of this file? If not make them private?

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/BasicAuthenticationFilter.java
> +        if (authHeader != null && authHeader.startsWith(AUTHORIZATION_BASIC)) {
You can escape this function early and throw an exception if the auth header is null.

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/BasicAuthenticationFilter.java
> +        if (authHeader != null && authHeader.startsWith(AUTHORIZATION_BASIC)) {
Also what would be the case that the auth header does not start with `Basic `?

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/BasicAuthenticationFilter.java
> +            var data = authHeader.substring(AUTHORIZATION_BASIC.length() + 1);
Can you not split the auth header into an array of substrings by the means of the space rather? i.e `Bearer asdfjasdfdslkj` would split into `["Bearer", "asdfjasdfdslkj"]`?

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/BasicAuthenticationFilter.java
> +            if (!data.isEmpty()) {
You can invert this check and handle the is empty scenario with an exception if that scenario should not occur. This will allow you to remove the extra level of indentation allowing your code to be easier to read and more maintainable.

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/config/WebSecurityConfig.java
> +                .addFilterBefore(basicAuthFilter, UsernamePasswordAuthenticationFilter.class);
Does this not define 2 types of authentication that you are trying to use? I think you should rather be trying to use an Oauth implementation with JWT instead of basic authentication.

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/JwtAuthenticationFilter.java
> +    public static final String AUTHORIZATION_BEARER = "Bearer";
```suggestion
    private static final String HEADER_AUTHORIZATION = "Authorization";
    private static final String AUTHORIZATION_BEARER = "Bearer";
```

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/JwtAuthenticationFilter.java
> +        }
Invert the check to see if the auth header is null and throw an exception if it is.

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/AuthController.java
> +    public ResponseEntity<AuthenticationResponse> authenticate() {
Should the authentication endpoint not consume a username and a password, verify their is an active user with those credentials and then return the generated JWT? I think this would then eliminate the need for the basic authentication service?

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/CrudController.java
> +        if (!readOnly) {
What is the use case whereby you would need your post endpoint to be readonly?

2023-04-18 14:49 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +        setReadOnly(true);
How do you handle the use case where you need to update your user? Your controller should not be readonly in that case.

2023-04-21 16:35 UTC, colsen-neslo requested changes

2023-04-21 16:35 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/JwtAuthenticationFilter.java
> +                processJwtToken(request);
Small but we like the standard of keeping the curly braces present for if statements, just keeps the scope definition more defined and explicit.

2023-04-21 16:35 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/model/AuthorizationRequest.java
> +    private String Password;
```suggestion
    private String username;
    private String password;
```

2023-04-24 07:26 UTC, colsen-neslo approved these changes

2023-04-24 08:28 UTC, JOlsen-Neslo requested changes

2023-04-24 08:28 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/JwtAuthenticationFilter.java
> +            String path = request.getRequestURI();
mark as final

2023-04-24 08:28 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/JwtAuthenticationFilter.java
> +        } catch (InvalidAuthorizationRequest e) {
mark as final

2023-04-24 08:28 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/auth/filter/JwtAuthenticationFilter.java
> +        var authArray = authHeader.split("\\s+");
mark as final

2023-04-24 08:28 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/CrudController.java
> +        if (isReadEnabled) {
I'm not understanding what the reasoning is behind this?

2023-04-24 10:43 UTC, JOlsen-Neslo approved these changes

2023-04-24 10:43 UTC, merged