TRAIN-253: Add users api get by username method.
r-barlow/train-spring-boot-insight pull request #35
Opened 2023-04-28 06:58 UTC by r-barlow

2023-04-28 07:17 UTC, colsen-neslo requested changes

2023-04-28 07:17 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +    @RequestMapping("find/{username}")
You can potential use a query parameter instead of a path parameter. This will also then make sure the paths still follow the correct pattern. i.e `/api/v1/users?username=exampleusername`

2023-05-03 12:02 UTC, colsen-neslo approved these changes

2023-05-04 07:33 UTC, JOlsen-Neslo requested changes

2023-05-04 07:33 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/controller/UserController.java
> +    public ResponseEntity<User> get(final @RequestParam("username") String username) {
Since you are finding an individual user, shouldn't this be a path parameter rather than a query parameter?

2023-05-05 09:43 UTC, JOlsen-Neslo approved these changes

2023-05-05 09:43 UTC, merged