TRAIN-268: Make exceptions return json instead of text.
r-barlow/train-spring-boot-insight pull request #36
Opened 2023-05-08 09:29 UTC by r-barlow

2023-05-09 08:01 UTC, colsen-neslo requested changes

2023-05-09 08:01 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/handler/RestExceptionHandler.java
> +        return handleExceptionInternal(exception, String.format("{ \"message\": \"%s\"}", exception.getMessage()), headers,
So an alternative to creating a formatted string response json object, you can create a generic API error object that can consume some information like the error message, the reason for the error, the response type, etc. You can then just return a repsponse entity of the error type with all the information and it should then be mapped to json.

2023-05-09 08:01 UTC, colsen-neslo commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Should this not be set to update?

2023-05-10 09:02 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/handler/RestExceptionHandler.java
> +                                       new HttpHeaders(), HttpStatus.NOT_FOUND, request);
What does this method do internally? Does it respond with the same status that you are providing?

2023-05-10 09:06 UTC, r-barlow commented on src/main/java/za/co/neslotech/spring/trainspringbootinsight/handler/RestExceptionHandler.java
> +                                       new HttpHeaders(), HttpStatus.NOT_FOUND, request);
It returns a ResponseEntity<Object> with the status code, object and defined headers. It is a built in method.

2023-05-10 10:13 UTC, JOlsen-Neslo approved these changes

2023-05-11 09:43 UTC, TristanCarswell approved these changes

2023-05-11 09:46 UTC, colsen-neslo approved these changes

2023-05-11 09:46 UTC, merged